Update sonarqube02.yaml

diff --git a/sonarqube02.yaml b/sonarqube02.yaml
--- a/sonarqube02.yaml
+++ b/sonarqube02.yaml
@@ -29,7 +29,14 @@ phases:
     commands:
       - >-
         QG_STATUS=$(curl -s -u sqp_b98738fa7d33bf28149480a3f793c9eb8715d468: "http://3.137.161.44:9000/api/qualitygates/project_status?projectKey=amr-test" | jq -r '.projectStatus.status');
-        if [ "$QG_STATUS" = "OK" ]; then echo "Quality gate passed"; else echo "Quality gate failed"; exit 1; fi
+        if [ "$QG_STATUS" = "OK" ]; then
+          echo "Quality gate passed";
+          export UPLOAD_ARTIFACTS=true;
+        else
+          echo "Quality gate failed";
+          export UPLOAD_ARTIFACTS=false;
+          exit 1;
+        fi
 
 artifacts:
   files:
@@ -37,6 +44,7 @@ artifacts:
   name: build-$(date +%Y-%m-%d-%H-%M-%S)
   discard-paths: yes
   base-directory: .
+  if: UPLOAD_ARTIFACTS == true
   s3:
     bucket: amr-demooo
-    path: amr-artifacts
+    path: amr-artifacts/$(date +%Y-%m-%d-%H-%M-%S)
