Update sonarqube02.yaml

diff --git a/sonarqube02.yaml b/sonarqube02.yaml
--- a/sonarqube02.yaml
+++ b/sonarqube02.yaml
@@ -8,18 +8,17 @@ phases:
       - unzip sonar-scanner-*.zip -d /opt
       - export PATH="/opt/sonar-scanner-5.0.1.3006-linux/bin:$PATH"
       - TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
-      - echo "BUILD_TIMESTAMP=${TIMESTAMP}" >> build_env
+      - echo "TIMESTAMP=${TIMESTAMP}" > timestamp.env
 
   pre_build:
     commands:
-      - source build_env
-      - echo "Build timestamp: ${BUILD_TIMESTAMP}"
+      - source timestamp.env
       - coverage run -m unittest discover -s . -p "test_*.py"
       - coverage report
 
   build:
     commands:
-      - source build_env
+      - source timestamp.env
       - coverage xml
       - >
         sonar-scanner
@@ -32,25 +31,25 @@ phases:
 
   post_build:
     commands:
-      - source build_env
-      - >
+      - source timestamp.env
+      - |
         QG_STATUS=$(curl -s -u sqp_102b7169fc001c55066ecfd3c41ceb60bd962f10: "http://52.15.229.182:9000/api/qualitygates/project_status?projectKey=amr-test" | jq -r '.projectStatus.status')
-        if [ "${QG_STATUS}" = "OK" ]; then
-          echo "Creating artifact directory: artifacts/${BUILD_TIMESTAMP}";
-          mkdir -p "artifacts/${BUILD_TIMESTAMP}";
-          mv coverage.xml test-reports/ target/ sonar-project.properties "artifacts/${BUILD_TIMESTAMP}/";
+        if [ "$QG_STATUS" = "OK" ]; then
+          echo "Creating artifact directory: artifacts/$TIMESTAMP"
+          mkdir -p "artifacts/$TIMESTAMP"
+          mv coverage.xml test-reports/ target/ "artifacts/$TIMESTAMP/"
         else
-          echo "Cleaning failed build outputs";
-          rm -rf coverage.xml test-reports/ target/;
-          exit 1;
+          echo "Cleaning failed build outputs"
+          rm -rf coverage.xml test-reports/ target/
+          exit 1
         fi
 
 artifacts:
   files:
     - '**/*'
-  name: build-${BUILD_TIMESTAMP}
+  name: build-$TIMESTAMP
   discard-paths: no
   base-directory: artifacts
   s3:
     bucket: amr-demooo
-    path: amr-artifacts/${BUILD_TIMESTAMP}/
+    path: amr-artifacts/$TIMESTAMP/
