Update sonarqube03-latest

diff --git a/sonarqube03-latest b/sonarqube03-latest
--- a/sonarqube03-latest
+++ b/sonarqube03-latest
@@ -29,4 +29,11 @@ phases:
     commands:
       - >-
         QG_STATUS=$(curl -s -u sqp_b98738fa7d33bf28149480a3f793c9eb8715d468: "http://3.137.161.44:9000/api/qualitygates/project_status?projectKey=amr-test" | jq -r '.projectStatus.status');
-        if [ "$QG_STATUS" = "OK" ]; then echo "Quality gate passed"; else echo "Quality gate failed"; exit 1; fi
+        if [ "$QG_STATUS" = "OK" ]; then
+          echo "Quality gate passed";
+          TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S);
+          aws s3 cp --recursive . s3://amr-demooo/amr-artifacts/$TIMESTAMP/;
+        else
+          echo "Quality gate failed";
+          exit 1;
+        fi
