Update sonarqube02.yaml

diff --git a/sonarqube02.yaml b/sonarqube02.yaml
--- a/sonarqube02.yaml
+++ b/sonarqube02.yaml
@@ -28,13 +28,17 @@ phases:
         sonar-scanner
         -Dsonar.projectKey=amr-test
         -Dsonar.host.url=http://3.16.139.210:9000
-        -Dsonar.login=squ_8056cef7d6722a87d2fca6976d8e81d0338c179f
+        -Dsonar.token=sqp_a2967e11fd2274239b965d007d70e2c399422fb9
         -Dsonar.sources=.
         -Dsonar.python.coverage.reportPaths=coverage.xml
 
   post_build:
     commands:
-      # Check and print quality gate status
       - >
         QG_STATUS=$(curl -s -u sqp_a2967e11fd2274239b965d007d70e2c399422fb9: http://3.16.139.210:9000/api/qualitygates/project_status?projectKey=amr-test | jq -r '.projectStatus.status')
-        if [ "$QG_STATUS" = "OK" ]; then echo "Quality gate passed"; else echo "Quality gate failed"; exit 1; fi
+        if [ "$QG_STATUS" = "OK" ]; then
+          echo "Quality gate passed"
+        else
+          echo "Quality gate failed"
+          exit 1
+        fi
